### ISSUE TITLE
[question] I don't understand the swipe repl demo

### ISSUE THREAD

**Issue by fredguth** [Rezi/svelte-gestures#13] opened 2022-08-03 22:38 UTC
I am taking a look in the swipe repl demo and nothing happens in my computer.  I tried to inspect the page and toggled device for mobile, but still doesnt' work.  Unfortunately, the page never opens in my iphone (safari). 

Am I doing something wrong here?

**Comment by Rezi** [comment] 2022-08-05 07:10
Sorry for having troubles. I'll need to check the behaviour from Safari on iPhone, hopefully I'll do that during weekend.

**Comment by nsakovich** [comment] 2022-11-18 13:28
@fredguth i think a possible reason of this issue is optional chaining syntax which is supported since Safari version 13.4 https://caniuse.com/mdn-javascript_operators_optional_chaining. So if your version is older it will not work for you. As possible workaround is to use @babel/plugin-proposal-optional-chaining plugin during the build process

**Comment by nsakovich** [comment] 2022-11-18 13:38
i have created PR for this https://github.com/Rezi/svelte-gestures/pull/16/files

**Comment by nsakovich** [comment] 2022-11-25 13:15
hi, i was able to reproduce this issue on my mac with Safari 12.0.1

**Comment by Rezi** [comment] 2023-05-17 21:52
Should be fixed in 1.5. I have removed the optional chaining syntax from build in cjs format. ES module format still uses it. Es modules can be used in modern browsers anyway or by other tools which compile the code to desired ES version.
if it is still issue even in the ES module format, let me know. I am preferring now smaller bundle for ES module ;)

**Closed by Rezi** 2023-05-17 21:52 UTC
